language: objective-c
osx_image: xcode7.2
script:
  xctool -project Advance.xcodeproj -scheme 'Advance-iOS' -configuration Debug -sdk iphonesimulator -arch i386 test
  xctool -project Advance.xcodeproj -scheme 'Advance-OSX' -configuration Debug test
